### ISSUE TITLE
Makefile: change "Template"

### ISSUE THREAD

**Issue by phdsg** [NonLinearInstruments/NLNRI_VCVRackPlugins#1]
https://github.com/NonLinearInstruments/NLNRI_VCVRackPlugins/blob/c0eebfe5a4dc6fa87c0d6ef2fa0f83ba42da1303/Makefile#L20

**Comment by NonLinearInstruments** [comment]
what should I use there ?

**Comment by NonLinearInstruments** [comment]
OH !! I see ... fixed ;)
