### ISSUE TITLE
Some module knobs missing with 0.6 update

### ISSUE THREAD

**Issue by cschol** [NonLinearInstruments/NLNRI_VCVRackPlugins#11]
On Linux:

![nlnri](https://user-images.githubusercontent.com/624427/37569570-d16db2e6-2aa9-11e8-915f-71d9309fe9bf.png)

**Comment by NonLinearInstruments** [comment]
Hi there, I'm on the process of cleaning it up all and make it compilable under 0.6.0 This fixes your issue. Thanks :)
