### ISSUE TITLE
Luci8x8_base.vcv not opening in Rack 0.6 (Win)

### ISSUE THREAD

**Issue by permadeath** [NonLinearInstruments/NLNRI_VCVRackPlugins#12]
The base patch for Luci is not opening in Rack 0.6 (Win).  There is an error message that says:

JSON parsing error at <stream> 7:1 '[' or '{' expected near '<'

**Comment by dizzisound** [comment]
@NonLinearInstruments I couldn't verify this issue on the 0.6 release, but I think that with the V1 version this problem is overcome, at least I could open the _Luci8x8_base.vcv_ base patch without errors, except that... it's a huge thing! So I suggest the present issue can be closed.
