### ISSUE TITLE
Update to VCV Rack v1

### ISSUE THREAD

**Issue by pgatt** [NonLinearInstruments/NLNRI_VCVRackPlugins#13]
Hi just wondering if there's any chance of seeing your modules in the latest version of Rack?

**Comment by NonLinearInstruments** [comment]
Hi, thanks for your interest, but I'm afraid I'm much too busy in other things. Sorry ... and feel free to fork !!

**Comment by dizzisound** [comment]
@NonLinearInstruments Just opened a [PR](https://github.com/NonLinearInstruments/NLNRI_VCVRackPlugins/pull/14) for merging the V1 ported version. Cheers!
