### ISSUE TITLE
compiler error:

### ISSUE THREAD

**Issue by phdsg** [NonLinearInstruments/NLNRI_VCVRackPlugins#2]
https://github.com/NonLinearInstruments/NLNRI_VCVRackPlugins/blob/75e0ee7d07cec9e0b97cf4e68ec60a64c5fbade9/src/QU4DiT.cpp#L67

OS: win (mingw64)
Rack: dev
plugin: dev

> $ make
g++  -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_WIN -D_USE_MATH_DEFINES  -Wsuggest-override -std=c++11 -c -o build/src/QU4DiT.cpp.o src/QU4DiT.cpp
src/QU4DiT.cpp: In member function 'virtual void QU4DiT::step()':
src/QU4DiT.cpp:67:29: error: 'isfinite' was not declared in this scope
  outputs[XN_OUTPUT].value = isfinite(x_out) ? x_out : 0.f;
                             ^~~~~~~~
src/QU4DiT.cpp:67:29: note: suggested alternative:
In file included from ../../include/math.hpp:5:0,
                 from ../../include/rack.hpp:4,
                 from src/NonLinearInstruments.hpp:1,
                 from src/QU4DiT.cpp:1:
H:/devel/msys64/mingw64/include/c++/7.2.0/cmath:585:5: note:   'std::isfinite'
     isfinite(_Tp __x)
     ^~~~~~~~
make: *** [../../compile.mk:54: build/src/QU4DiT.cpp.o] Error 1

this has been an issue in other people's modules too. can be fixed by using `std::isfinite()`

**Comment by NonLinearInstruments** [comment]
OK, thanks ... will fix it in next commit.
