### ISSUE TITLE
build fails with isfinite

### ISSUE THREAD

**Issue by davephillips** [NonLinearInstruments/NLNRI_VCVRackPlugins#3]
Linux Fedora 23 GCC 5.3.1
Rack 0.5.0

g++  -fPIC -I../../include -I../../dep/include -MMD -g -O3 -march=nocona -ffast-math -fno-finite-math-only -Wall -Wextra -Wno-unused-parameter -DARCH_LIN  -Wsuggest-override -std=c++11 -c -o build/src/QU4DiT.cpp.o src/QU4DiT.cpp
src/QU4DiT.cpp: In member function ‘virtual void QU4DiT::step()’:
src/QU4DiT.cpp:67:43: error: ‘isfinite’ was not declared in this scope
  outputs[XN_OUTPUT].value = isfinite(x_out) ? x_out : 0.f;
                                           ^
src/QU4DiT.cpp:67:43: note: suggested alternative:
In file included from ../../include/math.hpp:5:0,
                 from ../../include/rack.hpp:4,
                 from src/NonLinearInstruments.hpp:1,
                 from src/QU4DiT.cpp:1:
/usr/include/c++/5.3.1/cmath:601:5: note:   ‘std::isfinite’
     isfinite(_Tp __x)
     ^
../../compile.mk:53: recipe for target 'build/src/QU4DiT.cpp.o' failed
make: *** [build/src/QU4DiT.cpp.o] Error 1

**Comment by phdsg** [comment]
same behavior on windows. already filed.

**Comment by davephillips** [comment]
Our paths crossed. :) I also found the same solution as you did, std::isfinite works here too.

**Comment by NonLinearInstruments** [comment]
Hi, thanks to both for this. Fixed now.
