### ISSUE TITLE
load fail with latest source

### ISSUE THREAD

**Issue by davephillips** [NonLinearInstruments/NLNRI_VCVRackPlugins#4]
Linux Fedora 23
Rack 0.5.1

I build your modules from source, so I'm surprised by this error:

Failed to load library ./plugins/NLNRI_VCVRackPlugins/plugin.so: ./plugins/NLNRI_VCVRackPlugins/plugin.so: undefined symbol: _ZN16QU4DiTplusWidgetC1Ev

Any suggestions ?

**Comment by NonLinearInstruments** [comment]
Yep, found it and fixed, thanks.
Please confirm if it builds now.

**Comment by davephillips** [comment]
Thanks, the plugin now loads without error. Btw, have you removed the QU4ditPlus module ?

**Comment by NonLinearInstruments** [comment]
Ok, thanks for the info. Yes, QU4DiT+ did not go anywhere ... may be I'll retake it later.
