### ISSUE TITLE
plugin manager 

### ISSUE THREAD

**Issue by ghost** [NonLinearInstruments/NLNRI_VCVRackPlugins#6]
hi! 

I m going to support Andrew with the plugin manager.

pls check your makefile and compare it with the makefile in the tutorial ;)
this will help you to solve the issue!

you can ask me about help on FB aswell (Struggl Michael)
Talk soon!

**Comment by NonLinearInstruments** [comment]
Hi there !!

pleased to meet You :)

... yes, I've found the new makefile things ... already did it and now
awaiting for someone in the fb group to compile a linux dist (the win
version took 10 minutes only... this group is amazing !!)

Will pull request it thru the community repo soon...

see you


I.



2017-12-24 4:32 GMT+01:00 Phal-anx <notifications@github.com>:
