### ISSUE TITLE
Bad links in README.md

### ISSUE THREAD

**Issue by OSHChip-Owner** [NonLinearInstruments/NLNRI_VCVRackPlugins#9]
The following links have problems:

In the section for Luci:
   "After installing the package, user is suggested to Load the Luci8x8.vcv patch found here"
gives a 404 error if clicked

   "Please find here the user manual"
clicking on this does not result in a downloadable PDF.  
Also fails on the releases page.

Similar problems in the  "BallisticENV module" section

**Comment by NonLinearInstruments** [comment]
Fixed ... strangely enough looks like github somehow corrupts .pdf files ? anyway, got rid of it.
Thanks :)
